from app.models.alerta import Alerta
from app.models.ambiente import Ambiente
from app.models.articulo import Articulo
from app.models.articulo_caracteristica import Articulo_caracteristica
from app.models.asignacion import Asignacion
from app.models.caracteristica import Caracteristica
from app.models.categoria import Categoria
from app.models.historial_revision import HistorialRevision
from app.models.inventario_ambiente import InventarioAmbiente
from app.models.login_auditoria import Login_auditoria
from app.models.movimiento import Movimiento
from app.models.reporte import Reporte
from app.models.rol import Rol
from app.models.solicitud import Solicitud
from app.models.usuario import Usuario
